### ISSUE TITLE
Error setting framerate

### ISSUE THREAD

**Issue by samuelpowell** [ianshmean/SpinnakerGUI.jl#4]
It transpires that setting the framerate, as done in SpinnakerGUI at initialisation, fails unless I explicitly set `AcquistionFrameRateEnable` to true. 

I can update Spinnaker to do this automatically, but do all cameras require this? How about your grasshoper @ianshmean, does it have this node?

![acqmode](https://user-images.githubusercontent.com/6370657/57585882-dd430300-74e5-11e9-8bc8-5730d4072e9d.png)
![acqfr](https://user-images.githubusercontent.com/6370657/57585883-dddb9980-74e5-11e9-82f4-6304787f11f4.png)

**Comment by IanButterworth** [comment]
Ah! Ok, it does have that node. Yeah, I assume it's standard.

**Comment by samuelpowell** [comment]
Fixed in Spinnaker.jl (4ecc4b0847c7a3cf7d3f7a10b8448039e916f3de)
