### ISSUE TITLE
Paucity of screenshots

### ISSUE THREAD

**Issue by samuelpowell** [ianshmean/SpinnakerGUI.jl#5]
A package of this ilk deserves a screenshot, preferably one where the author appears in the video preview, or even better, a printed image of the author's github avatar, etc.

**Comment by samuelpowell** [comment]
Fixed in 919fa4994c440d862f883170f9fd8aa13f049be1

**Comment by IanButterworth** [comment]
Thanks for monitoring this closely and reacting promptly

**Comment by samuelpowell** [comment]
I try to keep on top of the important stuff
